/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthMessage */
        AuthMessage: {
            /** Token */
            token: string;
            /**
             * Type
             * @constant
             */
            type: "auth";
        };
        /** BranchInfo */
        BranchInfo: {
            /** Ahead */
            ahead: number | null;
            /** Behind */
            behind: number | null;
            /** Full Ref */
            full_ref: string;
            /** Is Current */
            is_current: boolean;
            /** Is Remote */
            is_remote: boolean;
            /** Last Commit Sha */
            last_commit_sha: string;
            /** Last Commit Subject */
            last_commit_subject: string;
            /** Last Commit Ts */
            last_commit_ts: number;
            /** Name */
            name: string;
            /** Upstream */
            upstream: string | null;
        };
        /** Branches */
        Branches: {
            /** Local */
            local: components["schemas"]["BranchInfo"][];
            /** Remote */
            remote: components["schemas"]["BranchInfo"][];
        };
        /** CheckoutBody */
        CheckoutBody: {
            /**
             * Branch
             * @default null
             */
            branch: string | null;
            /**
             * Create
             * @default null
             */
            create: string | null;
            /**
             * Force
             * @default false
             */
            force: boolean;
            /**
             * Start Point
             * @default null
             */
            start_point: string | null;
        };
        /** CommitBody */
        CommitBody: {
            /**
             * Amend
             * @default false
             */
            amend: boolean;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /** CommitDetail */
        CommitDetail: {
            /** Author */
            author: string;
            /** Body */
            body: string;
            /** Email */
            email: string;
            /** Files */
            files: components["schemas"]["CommitFile"][];
            /** Parents */
            parents: string[];
            /** Sha */
            sha: string;
            /** Subject */
            subject: string;
            /** Timestamp */
            timestamp: number;
        };
        /** CommitFile */
        CommitFile: {
            /** Orig Path */
            orig_path: string | null;
            /** Path */
            path: string;
            /**
             * Status
             * @enum {string}
             */
            status: "M" | "A" | "D" | "R" | "C" | "T" | "U";
        };
        /** DeleteBranchBody */
        DeleteBranchBody: {
            /**
             * Force
             * @default false
             */
            force: boolean;
            /** Name */
            name: string;
        };
        /** Diff */
        Diff: {
            /** Binary */
            binary: boolean;
            /** Hunks */
            hunks: components["schemas"]["DiffHunk"][];
            /** Path */
            path: string;
            /** Truncated */
            truncated: boolean;
        };
        /** DiffHunk */
        DiffHunk: {
            /** Header */
            header: string;
            /** Lines */
            lines: components["schemas"]["DiffLine"][];
            /** New Lines */
            new_lines: number;
            /** New Start */
            new_start: number;
            /** Old Lines */
            old_lines: number;
            /** Old Start */
            old_start: number;
        };
        /** DiffLine */
        DiffLine: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "context" | "add" | "del";
            /** New No */
            new_no: number | null;
            /** Old No */
            old_no: number | null;
            /** Text */
            text: string;
        };
        /** DiffSplitBody */
        DiffSplitBody: {
            /** Path */
            path: string;
            /**
             * Staged
             * @default false
             */
            staged: boolean;
        };
        /** ErrorBody */
        ErrorBody: {
            code: components["schemas"]["ErrorCode"];
            /** Message */
            message: string;
            /**
             * Stderr
             * @default
             */
            stderr: string;
        };
        /**
         * ErrorCode
         * @enum {string}
         */
        ErrorCode: "NOT_A_REPO" | "CONFLICT" | "AUTH_REQUIRED" | "NON_FAST_FORWARD" | "LOCKED" | "DIRTY_TREE" | "INVALID_PATH" | "INVALID_ARGUMENT" | "UNSUPPORTED" | "GIT_FAILED" | "UNAUTHORIZED" | "FORBIDDEN" | "STALE_CURSOR";
        /** FileChange */
        FileChange: {
            /**
             * Orig Path
             * @default null
             */
            orig_path: string | null;
            /** Path */
            path: string;
            /**
             * Status
             * @enum {string}
             */
            status: "M" | "A" | "D" | "R" | "C" | "T" | "U";
        };
        /** GraphCommit */
        GraphCommit: {
            /** Author */
            author: string;
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
            /** Lane */
            lane: number;
            /** Parents */
            parents: string[];
            /** Refs */
            refs: string[];
            /** Sha */
            sha: string;
            /** Subject */
            subject: string;
            /** Timestamp */
            timestamp: number;
        };
        /** GraphEdge */
        GraphEdge: {
            /** From Lane */
            from_lane: number;
            /**
             * Half
             * @enum {string}
             */
            half: "top" | "bottom";
            /** To Lane */
            to_lane: number;
        };
        /** GraphPage */
        GraphPage: {
            /** Commits */
            commits: components["schemas"]["GraphCommit"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Head */
        Head: {
            /** Branch */
            branch: string | null;
            /** Detached Sha */
            detached_sha: string | null;
        };
        /** OpDoneMessage */
        OpDoneMessage: {
            /** @default null */
            error: components["schemas"]["ErrorBody"] | null;
            /** Ok */
            ok: boolean;
            /** Op Id */
            op_id: string;
            /**
             * Type
             * @default op_done
             * @constant
             */
            type: "op_done";
        };
        /** OpProgressMessage */
        OpProgressMessage: {
            /** Line */
            line: string;
            /** Op Id */
            op_id: string;
            /**
             * Pct
             * @default null
             */
            pct: number | null;
            /** Phase */
            phase: string;
            /**
             * Type
             * @default op_progress
             * @constant
             */
            type: "op_progress";
        };
        /** OpStarted */
        OpStarted: {
            /** Op Id */
            op_id: string;
        };
        /** PathsBody */
        PathsBody: {
            /** Paths */
            paths: string[];
        };
        /** RenameBranchBody */
        RenameBranchBody: {
            /** New Name */
            new_name: string;
            /** Old Name */
            old_name: string;
        };
        /** RepoSnapshot */
        RepoSnapshot: {
            /** Conflicted */
            conflicted: components["schemas"]["FileChange"][];
            head: components["schemas"]["Head"];
            /** Root */
            root: string;
            /** Staged */
            staged: components["schemas"]["FileChange"][];
            /** Stash Count */
            stash_count: number;
            /**
             * State
             * @enum {string}
             */
            state: "clean" | "merging" | "rebasing" | "cherry-picking";
            /** @default null */
            theme: components["schemas"]["Theme"] | null;
            /** Unstaged */
            unstaged: components["schemas"]["FileChange"][];
            /** Untracked */
            untracked: string[];
            upstream: components["schemas"]["Upstream"] | null;
        };
        /** SnapshotMessage */
        SnapshotMessage: {
            repo: components["schemas"]["RepoSnapshot"] | null;
            /**
             * Shell Integration
             * @default true
             */
            shell_integration: boolean;
            /**
             * Type
             * @default snapshot
             * @constant
             */
            type: "snapshot";
        };
        /** StashEntry */
        StashEntry: {
            /** Index */
            index: number;
            /** Message */
            message: string;
            /** Sha */
            sha: string;
            /** Timestamp */
            timestamp: number;
        };
        /** StashIndexBody */
        StashIndexBody: {
            /** Index */
            index: number;
        };
        /** StashList */
        StashList: {
            /** Entries */
            entries: components["schemas"]["StashEntry"][];
        };
        /** StashPushBody */
        StashPushBody: {
            /**
             * Include Untracked
             * @default false
             */
            include_untracked: boolean;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /**
         * Theme
         * @description Both appearance palettes, plus the profile's monospace font.
         *
         *     Both palettes always travel, because a macOS light/dark switch fires no
         *     iTerm2 event: with a single palette the panel would keep the stale one
         *     until the next focus change. When the profile does not use separate
         *     light and dark colours the two palettes are identical.
         */
        Theme: {
            dark: components["schemas"]["ThemePalette"];
            light: components["schemas"]["ThemePalette"];
            /** Mono Family */
            mono_family: string;
            /** Mono Size */
            mono_size: number;
        };
        /**
         * ThemePalette
         * @description The profile colours the panel honours, for one system appearance.
         *
         *     The panel's own surfaces (backgrounds, separators, secondary text) are
         *     neutral and resolved in CSS from the system appearance, so the profile
         *     contributes only the colours that carry meaning: the user's diff green
         *     and red, and the accent used for branch and ref labels.
         */
        ThemePalette: {
            /** Accent */
            accent: string;
            /** Added */
            added: string;
            /** Removed */
            removed: string;
        };
        /** Upstream */
        Upstream: {
            /** Ahead */
            ahead: number;
            /** Behind */
            behind: number;
            /** Name */
            name: string;
        };
        /** UpstreamBody */
        UpstreamBody: {
            /** Name */
            name: string;
            /** Upstream */
            upstream: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
